### ISSUE TITLE
1.10 Support?

### ISSUE THREAD

**Issue by poblabs** [Sauilitired/ChatIcon#1]
Will you be able to add support for 1.10?

I get this error currently. 

```
[20:43:29 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'icon' in plugin ChatIcon v1.5
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-2486fb7-60c1719]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-2486fb7-60c1719]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:647) ~[spigot.jar:git-Spigot-2486fb7-60c1719]
        at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351) [spigot.jar:git-Spigot-2486fb7-60c1719]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186) [spigot.jar:git-Spigot-2486fb7-60c1719]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-2486fb7-60c1719]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-2486fb7-60c1719]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-2486fb7-60c1719]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-2486fb7-60c1719]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot.jar:git-Spigot-2486fb7-60c1719]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-2486fb7-60c1719]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot.jar:git-Spigot-2486fb7-60c1719]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot.jar:git-Spigot-2486fb7-60c1719]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_8_R2/entity/CraftPlayer
        at com.cyandev.plugin.chaticon.builder.ControlledSender.send(ControlledSender.java:15) ~[?:?]
        at com.cyandev.plugin.chaticon.builder.ChatMessage.send(ChatMessage.java:88) ~[?:?]
        at com.cyandev.plugin.chaticon.Command.onCommand(Command.java:39) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-2486fb7-60c1719]
        ... 15 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_8_R2.entity.CraftPlayer
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-Spigot-2486fb7-60c1719]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-2486fb7-60c1719]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_91]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_91]
        at com.cyandev.plugin.chaticon.builder.ControlledSender.send(ControlledSender.java:15) ~[?:?]
        at com.cyandev.plugin.chaticon.builder.ChatMessage.send(ChatMessage.java:88) ~[?:?]
        at com.cyandev.plugin.chaticon.Command.onCommand(Command.java:39) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-2486fb7-60c1719]
        ... 15 more
```

**Comment by poblabs** [comment]
Dead project
